import './globals.css'
import type { Metadata } from 'next'
import { Inter,Outfit } from 'next/font/google'
import CarProvider from '@/app/context/CarContext'
import { QueryProvider } from './context/QueryContext'
import RentalDuration from './components/RentalDuration'
const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <CarProvider>
      <QueryProvider>
      <body className={outfit.className}>
        <RentalDuration />
        {children}</body>
      </QueryProvider>
      </CarProvider>
      
    </html>
  )
}
